name: responsive_grid_list
description: A Flutter plugin to create responsive grid lists using ListView.builder() or SliverList with a SliverChildBuilderDelegate.
version: 1.2.5
homepage: https://htoenjes.de
repository: https://github.com/hauketoenjes/responsive_grid_list
issue_tracker: https://github.com/hauketoenjes/responsive_grid_list/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  test: ^1.21.1

flutter:
